# Generated by Django 2.2 on 2019-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50)),
                ('Book_name', models.CharField(max_length=50)),
                ('Author_name', models.CharField(max_length=20)),
            ],
        ),
    ]
