# Generated by Django 2.2 on 2019-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20190530_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50)),
                ('Book_name', models.CharField(max_length=50)),
                ('Author_name', models.CharField(max_length=20)),
                ('Student_name', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
