# Generated by Django 2.2.1 on 2019-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_auto_20190531_0542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
