# Generated by Django 2.2.1 on 2019-06-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20190610_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='datetime',
        ),
    ]
